### PR TITLE
feat: add slidev real-time preview 

### PR DESCRIPTION
**Pull request by ycjcl868**
image

### CODE REVIEW

**Comment by antfu** [comment]
This is AWESOME!! Thanks a lot!

**Comment by ycjcl868** [comment]
> This is AWESOME!! Thanks a lot!

How to get the slidev server port? It's hard-code(3030) in VSCode.

**Comment by antfu** [comment]
Not sure, probably better to just make it configurable

**Comment by Mickychen00** [comment]
Hi in my both Windows and Mac, only Slides module show the structure of my slides but preview is empty or show the slidev server is not found (default port 3030). But my edge browser can see this localhost:3030. What can I do? thx

**Pull request merged**
